/**
 * Generated by `npm run db:types` (supabase gen types typescript).
 * DO NOT EDIT BY HAND — regenerate after every migration.
 *
 * Placeholder until the first migration lands (task 1.2).
 */
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export type Database = any;
